const items = [
    {
        id: '001',
        image: '../wasteExchange/images/1.jpg',
        company: 'Metal Sheets',
        item_name: 'Plastic Kursi Scrap',
        original_price: 1045,
        current_price: " 60",
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            Material: 'metal',
            type: 'rods and sheets',
        },
    },
    {
        id: '002',
        image: '../wasteExchange/images/2.jpg',
        company: 'Organic Soil',
        item_name: 'Plastic Kursi Scrap',
        original_price: 2599,
        current_price: 15,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            Material: "organic waste",
            type: "Ogranic Soil",
        },
    },
    {
        id: '003',
        image: '../wasteExchange/images/3.jpg',
        company: 'Chair',
        item_name: 'Plastic Kursi Scrap',
        original_price: 1599,
        current_price: 80,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            Material: "Plastic waste",
            type: "Plastic",
        },
    },
    {
        id: '004',
        image: '../wasteExchange/images/1.jpg',
        company: 'Metal',
        item_name: 'Plastic Kursi Scrap',
        original_price: 9999,
        current_price: 50,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            Material: "metal waste",
            type: "Metal Waste",
        },
    },
    {
        id: '005',
        image: '../wasteExchange/images/1.jpg',
        company: 'E Waste',
        item_name: 'Plastic Kursi Scrap',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            Material: "Ewaste  waste",
            type: "Ewaste",
        },
    },
    {
        id: '006',
        image: '../wasteExchange/images/3.jpg',
        company: 'E waste',
        item_name: 'Plastic Kursi Scrap',
        original_price: 14995,
        current_price: 50,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            Material: "e waste  waste",
            type: "Ewaste Soil",
        },
    },
    {
        id: '007',
        image: '../wasteExchange/images/7.jpg',
        company: 'E waste Scrape',
        item_name: 'E waste Scrape',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            Material: "organic waste",
            type: "Ogranic Soil",
        },
    },
    {
        id: '008',
        image: '../wasteExchange/images/8.jpg',
        company: 'Cloths ',
        item_name: 'Plastic Kursi Scrap',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            Material: "organic waste",
            type: "Ogranic Soil",
        },
    }
];